abstract class FutreGymApisConfig {
  static const String futureGymToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJc3N1ZXIgb2YgdGhlIEpXVCIsImF1ZCI6IkF1ZGllbmNlIHRoYXQgdGhlIEpXVCIsInN1YiI6IlN1YmplY3Qgb2YgdGhlIEpXVCIsImlhdCI6MTY2ODI2OTU1NiwiZXhwIjoxNjY4MjczMTU2LCJlbWFpbCI6InRyYWluZXItdGVzdEB0ZXN0LmNvbSIsInVzZXJJRCI6IjEyMCJ9.QRMeQlMHmlgiMljgar-olEifTcD2AJCqI6QEVtorl7M';
static const String traineeToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJc3N1ZXIgb2YgdGhlIEpXVCIsImF1ZCI6IkF1ZGllbmNlIHRoYXQgdGhlIEpXVCIsInN1YiI6IlN1YmplY3Qgb2YgdGhlIEpXVCIsImlhdCI6MTY2ODMyMDczNiwiZXhwIjoxNjY4MzI0MzM2LCJlbWFpbCI6InRyYWluZWUtdGVzdEB0ZXN0LmNvbSIsInVzZXJJRCI6IjEyMSJ9.HCrnLaQEImuvXul6qSSY3ZwxGXx6TGSmDcjSzZPEbb0';
static const String url = 'https://future-gym.net/api';
}